### ISSUE TITLE
Repos list by state on dashboard

### ISSUE THREAD

**Issue by leplatrem** [twidi/github-issues-manager#163]
As a user, when I open the dashboard, I would like to easily see what are the issues that I need to consider, accross all the repos. Similarly, I would like to easily the repos where there issues that need to be considered.

Currently the repository list mainly shows repository names, whereas the number of issues (opened, assigned..) is not a primary information.

It would be great to have like accordeons, by state (with unread issues, with issues assigned to me, opened, no opened issue).

This way there would be an immediate way to see the repos where new issues were created or assigned to me since my last visit for example. (like Gmail's priority inbox).
But also be able to give a quick overlook at the repos where my intervention is still needed.

**Comment by twidi** [comment]
@leplatrem https://headwayapp.co/isshub-changelog/3206 :)
